# Generated by Django 3.2.9 on 2021-12-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zybrilca_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='text_pairs',
        ),
        migrations.CreateModel(
            name='WordPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40, verbose_name='Переводимое слово')),
                ('word_translation', models.CharField(max_length=40, verbose_name='Перевод')),
                ('dictionary_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zybrilca_app.dictionary')),
            ],
        ),
    ]
