# Generated by Django 3.2.9 on 2021-12-13 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Zybrilca_app', '0002_auto_20211212_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkForAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_value', models.FloatField(max_length=10)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zybrilca_app.dictionary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zybrilca_app.dictionary')),
                ('user_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('added_dictionary', 'user_added')},
            },
        ),
    ]
