# Generated by Django 3.2.9 on 2021-12-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zybrilca_app', '0003_bookmark_markforanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Пометка удаления'),
        ),
    ]
